---
title: "Fletcher"
output: html_document
---
```{r}
library(tidyverse)
library(RColorBrewer)
library(paletteer)
library(janitor)
library(gtools)
```

```{r}
fletcher_og <- read_csv("fletcher_og.csv")
names(fletcher_og)
```

```{r}
fletcher_names2 <- fletcher_og[1:2, ]
```

```{r}
fletcher_names3 <- fletcher_names2 %>%
  pivot_longer(everything(), names_to = "variable", values_to = "value") %>%
  # Add a row identifier
  mutate(row_id = rep(1:nrow(fletcher_names2), each = ncol(fletcher_names2))) %>%
  # Reshape back to wide format with rows as columns
  pivot_wider(names_from = row_id, values_from = value, names_prefix = "Row_")
fletcher_names3
```

```{r}
fletcher_names3 <- fletcher_names3 %>% 
  clean_names()
fletcher_names3
```

```{r}
fletcher_names4 <- fletcher_names3 %>% 
  #filter(is.na(row_2) == TRUE)
  mutate(new_names = case_when(is.na(row_1) == FALSE & is.na(row_2) == FALSE ~ paste(row_1, row_2, sep = " "), is.na(row_2) == TRUE ~ row_1, is.na(row_1) == TRUE ~ row_2)) %>%   mutate(new_names = ifelse(new_names == "Probability", "Bedrock Edition Probability", new_names))
```

```{r}
fletcher_names4$new_names <- str_remove(fletcher_names4$new_names, "\n")
fletcher_names4
```

```{r}
fletcher2 <- fletcher_og %>%
  rename_with(~ fletcher_names4$new_names) %>% 
  clean_names()
fletcher2 <- fletcher2[-c(1, 2), ]
fletcher2
```

```{r}
fletcher2.1 <- fletcher2 %>% 
  mutate(bedrock_edition_slot = case_when(villager_xp == "1" ~ "2", 
                           item_wanted == "2 × Emerald\n+ 5 × Arrow" ~ "10",
                           TRUE ~ bedrock_edition_slot))
fletcher2.1
```

```{r}
fletcher2.2 <- fletcher2.1 %>% 
  mutate(level = case_when(bedrock_edition_slot == "2" ~ "Novice", 
                           bedrock_edition_slot == "4" ~ "Apprentice",
                           bedrock_edition_slot == "6" ~ "Journeyman",
                           bedrock_edition_slot == "8" ~ "Expert",
                           bedrock_edition_slot == "10" ~ "Master",
                           TRUE ~ level))
fletcher2.2
```

```{r}
fletcher2.2$bedrock_edition_slot <- as.integer(fletcher2.2$bedrock_edition_slot)

fletcher2.2$bedrock_edition_probability <- str_remove(fletcher2.2$bedrock_edition_probability, "%")

fletcher2.2$bedrock_edition_probability <- as.integer(fletcher2.2$bedrock_edition_probability)

fletcher2.2$java_edition_probability <- str_remove(fletcher2.2$java_edition_probability, "%")

fletcher2.2$java_edition_probability <- as.integer(fletcher2.2$java_edition_probability)

fletcher2.2$trades_in_stock <- as.integer(fletcher2.2$trades_in_stock)

fletcher2.2$villager_xp <- as.integer(fletcher2.2$villager_xp)

fletcher2.2
```

```{r}
fletcher2.3 <- fletcher2.2 %>% 
  #mutate(if_else())
  separate(item_given, into= c("item_given", "garbage"), sep = "\\[")
fletcher2.3 <- fletcher2.3[ ,-7]
fletcher2.3
```

```{r}
fletcher2.4 <- fletcher2.3 %>% 
  #mutate(if_else())
  separate(item_wanted, into= c("item_wanted", "item_wanted_2"), sep = "\\+")

fletcher2.4$item_wanted <- str_remove(fletcher2.4$item_wanted, "\n")

fletcher2.4
```

```{r}
fletcher2.5 <- fletcher2.4 %>% 
  #mutate(if_else())
  separate(item_wanted, into= c("num_item_wanted", "item_wanted"), sep = "×") %>% 
  mutate(item_wanted = if_else(is.na(item_wanted) == TRUE, num_item_wanted, item_wanted)) %>% 
  mutate(num_item_wanted = if_else(num_item_wanted != item_wanted, num_item_wanted, "1"))
fletcher2.5
```

```{r}
fletcher2.6 <- fletcher2.5 %>% 
  #mutate(if_else())
  separate(item_wanted_2, into= c("num_item_wanted_2", "item_wanted_2"), sep = "×") %>% 
  mutate(item_wanted_2 = if_else(is.na(item_wanted_2) == TRUE, num_item_wanted_2, item_wanted_2)) %>% 
  mutate(num_item_wanted_2 = if_else(num_item_wanted_2 != item_wanted_2, num_item_wanted_2, "1")) %>% 
  mutate(num_item_wanted_2 = as.integer(num_item_wanted_2))
fletcher2.6
```

```{r}
fletcher2.7 <- fletcher2.6 %>% 
  #mutate(if_else())
  separate(num_item_wanted, into= c("low_range", "high_range"), sep = "–") %>% 
  mutate(high_range = if_else(is.na(high_range) == TRUE, low_range, high_range))

fletcher2.7$low_range = as.integer(fletcher2.7$low_range)
fletcher2.7$high_range = as.integer(fletcher2.7$high_range)

fletcher2.7
```

```{r}
fletcher2.8 <- fletcher2.7 %>% 
  #mutate(if_else())
  separate(item_given, into= c("num_item_given", "item_given"), sep = "×") %>% 
  mutate(item_given = if_else(is.na(item_given) == TRUE, num_item_given, item_given)) %>% 
  mutate(num_item_given = if_else(num_item_given != item_given, num_item_given, "1"))
fletcher2.8
```

```{r}
fletcher2.8 <- fletcher2.8 %>% 
  mutate(level = if_else(item_given != " Tipped Arrow", level, "Master")) %>% 
  mutate(bedrock_edition_slot = if_else(item_given != " Tipped Arrow", bedrock_edition_slot, 9))
```

##I am making more edits here to make this dataset cohesive

```{r}
cleaner_data <- fletcher2.8 %>%
  mutate(row_id = row_number())
```

```{r}
cleaner_data1 <- cleaner_data %>% 
  mutate(item_wanted = str_trim(item_wanted, side = "left")) %>% 
  mutate(item_wanted_2 = str_trim(item_wanted_2, side = "left")) %>% 
  mutate(item_given = str_trim(item_given, side = "left")) 
cleaner_data1$item_wanted <- str_remove(cleaner_data1$item_wanted, "\r")
cleaner_data1
```


```{r}
cleaner_data1.1 <- cleaner_data1 %>% 
  mutate(em_wanted = case_when(item_wanted_2 == "Emerald" ~ TRUE,
                               item_wanted == "Emerald" ~ TRUE,
                                TRUE ~ FALSE)) 
```

```{r}
cleaner_data1.1 <- cleaner_data1.1 %>% 
  mutate(num_em_want_low = ifelse(em_wanted == TRUE, low_range, NA)) %>% 
  mutate(num_em_want_high = ifelse(em_wanted == TRUE, high_range, NA))  %>% 
  mutate(num_em_want_low = ifelse(row_id == 3, 1, num_em_want_low)) %>% 
  mutate(num_em_want_high = ifelse(row_id == 3, 1, num_em_want_high))
cleaner_data1.1
```

```{r}
cleaner_data1.1 <- cleaner_data1.1 %>% 
  #mutate(num_item_wanted = as.integer(num_item_wanted)) %>% 
  mutate(num_item_want = case_when(item_wanted != "Emerald" ~ low_range,
                                   item_wanted_2 == "Arrow" ~ 5,
                                   TRUE ~ NA))
```

```{r}
cleaner_data1.1 <- cleaner_data1.1 %>% 
  mutate(item_wanted = if_else(item_wanted != "Emerald", item_wanted, NA)) %>% 
  mutate(item_wanted = if_else(row_id == 12, "Arrow", item_wanted))
```

```{r}
cleaner_data1.1 <- cleaner_data1.1 %>% 
  mutate(em_given = if_else(item_given == "Emerald", TRUE, FALSE))
```

```{r}
cleaner_data1.1 <- cleaner_data1.1 %>% 
  mutate(num_em_given = ifelse(em_given == TRUE, num_item_given, NA))  
```

```{r}
cleaner_data1.1 <- cleaner_data1.1 %>% 
  mutate(item_given = ifelse(item_given == "Emerald", NA, item_given))  
```

```{r}
cleaner_data1.1 <- cleaner_data1.1 %>% 
  mutate(num_item_given = ifelse(is.na(item_given) == TRUE, NA, num_item_given))  
```

```{r}
cleaner_data1.1 <- cleaner_data1.1 %>%
  mutate(trade = "Fletcher")
```

```{r}
cleaner_data1.1 <- cleaner_data1.1 %>% 
  select(row_id, trade, level, bedrock_edition_slot, bedrock_edition_probability, java_edition_probability, em_wanted, num_em_want_low, num_em_want_high, item_wanted, num_item_want, em_given, num_em_given, item_given, num_item_given, trades_in_stock, price_multiplier, villager_xp)
```

```{r}
write.csv(cleaner_data1.1, "fletcher_clean_2.csv", row.names = FALSE)
fletcher <- read_csv("fletcher_clean_2.csv")
```
