---
title: "Cartographer"
output: html_document
---
```{r}
library(tidyverse)
library(RColorBrewer)
library(paletteer)
library(janitor)
library(gtools)
```

```{r}
cartographer_og <- read_csv("cartographer_og.csv")
names(cartographer_og)
```

```{r}
cartographer_og_names_2 <- cartographer_og[1:2, ]
```

```{r}
cart_og_names3 <- cartographer_og_names_2 %>%
  pivot_longer(everything(), names_to = "variable", values_to = "value") %>%
  # Add a row identifier
  mutate(row_id = rep(1:nrow(cartographer_og_names_2), each = ncol(cartographer_og_names_2))) %>%
  # Reshape back to wide format with rows as columns
  pivot_wider(names_from = row_id, values_from = value, names_prefix = "Row_")
cart_og_names3
```

```{r}
cart_og_names3 <- cart_og_names3 %>% 
  clean_names()
cart_og_names3
```

```{r}
cart_og_names4 <- cart_og_names3 %>% 
  #filter(is.na(row_2) == TRUE)
  mutate(new_names = case_when(is.na(row_1) == FALSE & is.na(row_2) == FALSE ~ paste(row_1, row_2, sep = " "), is.na(row_2) == TRUE ~ row_1, is.na(row_1) == TRUE ~ row_2)) %>%   mutate(new_names = ifelse(new_names == "Probability", "Bedrock Edition Probability", new_names))
cart_og_names4
```

```{r}
cart_og_names4$new_names <- str_remove(cart_og_names4$new_names, "\n")
cart_og_names4
```

```{r}
cartographer2 <- cartographer_og %>%
  rename_with(~ cart_og_names4$new_names) %>% 
  clean_names()
cartographer2 <- cartographer2[-c(1, 2), ]
cartographer2
```

```{r}
cartographer2.1 <- cartographer2 %>% 
  mutate(level = case_when(bedrock_edition_slot == "2" ~ "Novice", 
                           bedrock_edition_slot == "4" ~ "Apprentice",
                           bedrock_edition_slot == "6" | bedrock_edition_slot == "7" ~ "Journeyman",
                           bedrock_edition_slot == "9" ~ "Expert",
                           TRUE ~ level))
cartographer2.1
```

```{r}
cartographer2.1$bedrock_edition_slot <- as.integer(cartographer2.1$bedrock_edition_slot)

cartographer2.1$bedrock_edition_probability <- str_remove(cartographer2.1$bedrock_edition_probability, "%")

cartographer2.1$bedrock_edition_probability <- as.integer(cartographer2.1$bedrock_edition_probability)

cartographer2.1$java_edition_probability <- str_remove(cartographer2.1$java_edition_probability, "%")

cartographer2.1$java_edition_probability <- as.integer(cartographer2.1$java_edition_probability)

cartographer2.1$trades_in_stock <- as.integer(cartographer2.1$trades_in_stock)

cartographer2.1$villager_xp <- as.integer(cartographer2.1$villager_xp)

cartographer2.1
```

```{r}
cartographer2.3 <- cartographer2.1 %>% 
  #mutate(if_else())
  separate(item_given, into= c("item_given", "garbage"), sep = "\\[")

cartographer2.3 <- cartographer2.3[ ,-7]
cartographer2.3
```

```{r}
cartographer2.4 <- cartographer2.3 %>% 
  #mutate(if_else())
  separate(item_wanted, into= c("num_item_wanted", "item_wanted"), sep = "×") %>% 
  mutate(item_wanted = if_else(is.na(item_wanted) == TRUE, num_item_wanted, item_wanted)) %>% 
  mutate(num_item_wanted = if_else(num_item_wanted != item_wanted, num_item_wanted, "1"))
cartographer2.4
```

```{r}
cartographer2.5 <- cartographer2.4 %>% 
  #mutate(if_else())
  separate(item_wanted, into= c("item_wanted_1", "item_wanted_2"), sep = "\n+") 
  #mutate(item_wanted_2 = if_else(is.na(item_wanted_2) == TRUE, item_wanted_1, item_wanted_2)) %>% 
  #mutate(item_wanted_1 = if_else(item_wanted_1 != item_wanted_2, item_wanted_1, "1"))

cartographer2.5$item_wanted_2 <- str_remove(cartographer2.5$item_wanted_2, "\\+ ")
cartographer2.5
```

##I am making more edits here to make this dataset cohesive

```{r}
cleaner_data <- cartographer2.5 %>%
  mutate(row_id = row_number())
```

```{r}
cleaner_data1 <- cleaner_data %>% 
  mutate(item_wanted_1 = str_trim(item_wanted_1, side = "left")) %>% 
  mutate(item_given = str_trim(item_given, side = "left")) 
cleaner_data1$item_wanted_1 <- str_remove(cleaner_data1$item_wanted_1, "\r")
cleaner_data1
```


```{r}
cleaner_data1.1 <- cleaner_data1 %>% 
  mutate(em_wanted = if_else(item_wanted_1 == "Emerald", TRUE, FALSE)) 
```

```{r}
cleaner_data1.1 <- cleaner_data1.1 %>% 
  mutate(num_em_want_low = ifelse(em_wanted == TRUE, num_item_wanted, NA)) %>% 
  mutate(num_em_want_high = ifelse(em_wanted == TRUE, num_item_wanted, NA))  
cleaner_data1.1
```

```{r}
cleaner_data1.1 <- cleaner_data1.1 %>% 
  mutate(num_item_wanted = as.integer(num_item_wanted)) %>% 
  mutate(num_item_want = case_when(item_wanted_1 != "Emerald" ~ num_item_wanted,
                                   item_wanted_2 == "Compass" ~ 1))
```

```{r}
cleaner_data1.1 <- cleaner_data1.1 %>% 
  mutate(item_wanted = case_when(item_wanted_1 != "Emerald" ~ item_wanted_1,
                              item_wanted_2 == "Compass" ~ item_wanted_2,
                              TRUE ~ NA))  
```

```{r}
cleaner_data1.1 <- cleaner_data1.1 %>% 
  mutate(em_given = if_else(item_given == "Emerald", TRUE, FALSE))
```

```{r}
cleaner_data1.1 <- cleaner_data1.1 %>% 
  mutate(num_em_given = ifelse(em_given == TRUE, 1, NA))  
```

```{r}
cleaner_data1.1 <- cleaner_data1.1 %>% 
  mutate(item_given = ifelse(item_given == "Emerald", NA, item_given))  
```

```{r}
cleaner_data1.1 <- cleaner_data1.1 %>% 
  mutate(num_item_given = ifelse(is.na(item_wanted) != FALSE, 1, NA))  
```

```{r}
cleaner_data1.1 <- cleaner_data1.1 %>%
  mutate(trade = "Cartographer")
```

```{r}
cleaner_data1.1 <- cleaner_data1.1 %>% 
  select(row_id, trade, level, bedrock_edition_slot, bedrock_edition_probability, java_edition_probability, em_wanted, num_em_want_low, num_em_want_high, item_wanted, num_item_want, em_given, num_em_given, item_given, num_item_given, trades_in_stock, price_multiplier, villager_xp)
```

```{r}
write.csv(cleaner_data1.1, "cartographer_clean_2.csv", row.names = FALSE)
cartographer <- read_csv("cartographer_clean_2.csv")
```

