---
title: "Group08"
output: html_document
date: "2025-02-27"
---
```{r}
library(tidyverse)
library(RColorBrewer)
library(paletteer)
library(janitor)
library(gtools)
```

```{r}
minecraft <- read_csv("minecraft_game_usage.csv") %>% 
  clean_names()
```
```{r}
names(minecraft)
```
Block building rank : 

```{r}
playtime <- minecraft %>% 
  mutate(player_type = playtime_minutes/60)
playtime

```
```{r}
quartile_playtime <- quantcut(playtime$player_type) 
  table(quartile_playtime)
```


```{r}
minecraft_playtime <- playtime %>% 
  mutate( player_type= case_when(player_type<=1.28 ~ "beginner",
                                   player_type>1.28 & player_type<=2.53 ~ "intermediate",
                                   player_type>2.53 & player_type<= 3.77 ~ "skilled",
                                   player_type>3.77 ~ "master"))
```

favorite tools : 
```{r}
minecraft_playtime %>% 
  group_by()
```
```{r}
minecraft_playtime %>% 
  ggplot(aes(tools_used,fill = player_type))+
  geom_bar(position = "dodge")
```

Game mode influence death 
```{r}
minecraft_playtime %>% 
  select(game_mode, deaths) %>% 
  group_by(game_mode) %>% 
  summarise(average_deaths=mean(deaths)) %>% 
  ggplot(aes(x=game_mode, y=average_deaths, fill=game_mode))+
  geom_col()
```

armor equiped related to death
```{r}
minecraft_playtime %>% 
  select(armor_equipped, deaths) %>% 
  group_by(armor_equipped) %>% 
  ggplot(aes(deaths))+
  geom_histogram(fill="pink", bins=10)+ 
  facet_wrap(~armor_equipped, labeller=label_both)
```
```{r}
minecraft_playtime %>% 
  select(armor_equipped, deaths) %>% 
  group_by(armor_equipped) %>% 
  summarise(average_deaths=mean(deaths)) %>% 
  ggplot(aes(x=armor_equipped, y=average_deaths, fill=armor_equipped))+
  geom_col()
```
armor equipped related to play time
```{r}
minecraft_playtime %>% 
  select(armor_equipped, player_type) %>%
  group_by(armor_equipped) %>%
  ggplot(aes(player_type,fill = armor_equipped))+
  geom_bar(position = "dodge")
```


