---
title: "VillagerCombo"
output: html_document
---

##this code does not work, I was unable to merge all of the data

```{r}
library(tidyverse)
library(tidyr)
library(RColorBrewer)
library(paletteer)
library(janitor)
library(gtools)
```

```{r}
Armorer <- read_csv("Armorer Data/armorer_sim_data.csv")
Butcher <- read_csv("Butcher Data/butcher_sim_data.csv")
Cartographer <- read_csv("Cartographer Data/cartographer_sim_data.csv")
Cleric <- read_csv("Cleric Data/cleric_sim_data.csv")
Farmer <- read_csv("Farmer Data/farmer_sim_data.csv")
Fisherman <- read_csv("Fisherman Data/fisherman_sim_data.csv")
Fletcher <- read_csv("Fletcher Data/fletcher_sim_data.csv")
Leatherworker <- read_csv("Leatherworker Data/leatherworker_sim_data.csv")
Librarian <- read_csv("Librarian Data/librarian_sim_data.csv")
Mason <- read_csv("Mason Data/mason_sim_data.csv")
Shepherd <- read_csv("Shepherd Data/shepherd_sim_data.csv")
Toolsmith <- read_csv("Toolsmith Data/toolsmith_sim_data.csv")
Weaponsmith <- read_csv("Weaponsmith Data/weaponsmith_sim_data.csv")

```

```{r}
Armorer <- Armorer %>% 
  mutate(row_id = row_number()) %>% 
  unite(row_id_trade, row_id, trade)
Butcher <- Butcher %>% 
  mutate(row_id = row_number()) %>% 
  unite(row_id_trade, row_id, trade)
Cartographer <- Cartographer %>% 
  mutate(row_id = row_number()) %>% 
  unite(row_id_trade, row_id, trade)
Cleric <- Cleric %>% 
  mutate(row_id = row_number()) %>% 
  unite(row_id_trade, row_id, trade)
Farmer <- Farmer %>% 
  mutate(row_id = row_number()) %>% 
  unite(row_id_trade, row_id, trade)
Fisherman <- Fisherman %>% 
  mutate(row_id = row_number()) %>% 
  unite(row_id_trade, row_id, trade)
Fletcher <- Fletcher %>% 
  mutate(row_id = row_number()) %>% 
  unite(row_id_trade, row_id, trade)
Leatherworker <- Leatherworker %>% 
  mutate(row_id = row_number()) %>% 
  unite(row_id_trade, row_id, trade)
Librarian <- Librarian %>% 
  mutate(row_id = row_number()) %>% 
  unite(row_id_trade, row_id, trade)
Mason <- Mason %>% 
  mutate(row_id = row_number()) %>% 
  unite(row_id_trade, row_id, trade)
Shepherd <- Shepherd %>% 
  mutate(row_id = row_number()) %>% 
  unite(row_id_trade, row_id, trade)
Toolsmith <- Toolsmith %>% 
  mutate(row_id = row_number()) %>% 
  unite(row_id_trade, row_id, trade)
Weaponsmith <- Weaponsmith %>%
  mutate(row_id = row_number()) %>% 
  unite(row_id_trade, row_id, trade)
```

```{r}
datasets <- list(Armorer, Butcher, Cartographer, Cleric, Farmer, Fisherman, Fletcher, Leatherworker, Librarian, Mason, Shepherd, Toolsmith, Weaponsmith)
```

```{r}
Villager_full <- Reduce(function(x, y) full_join(x, y, by = "row_id_trade"), datasets)

# Automatically coalesce columns with the same name
common_cols <- setdiff(names(Villager_full), "row_id_trade")  # Exclude the join key
for (col in common_cols) {
  duplicated_cols <- names(Villager_full)[grepl(paste0("^", col, "\\.x$|^", col, "\\.y$"), names(Villager_full))]
  if (length(duplicated_cols) > 0) {
    Villager_full <- Villager_full %>%
      mutate(!!col := coalesce(!!!syms(duplicated_cols))) %>%
      select(-all_of(duplicated_cols))
  }
}
```


```{r}
Villager_full <- Armorer %>%
  full_join(Butcher, by = "row_id_trade") %>%
  full_join(Cartographer, by = "row_id_trade") %>%
  full_join(Cleric, by = "row_id_trade") %>%
  full_join(Farmer, by = "row_id_trade") %>%
  full_join(Fisherman, by = "row_id_trade") %>%
  full_join(Fletcher, by = "row_id_trade") %>%
  full_join(Leatherworker, by = "row_id_trade") %>%
  full_join(Librarian, by = "row_id_trade") %>%
  full_join(Mason, by = "row_id_trade") %>%
  full_join(Shepherd, by = "row_id_trade") %>%
  full_join(Toolsmith, by = "row_id_trade") %>%
  full_join(Weaponsmith, by = "row_id_trade")
```

