---
title: "VillagerCombo"
output: html_document
---
```{r}
library(tidyverse)
library(tidyr)
library(RColorBrewer)
library(paletteer)
library(janitor)
library(gtools)
```

```{r}
Armorer <- read_csv("Armorer Data/armorer_clean_2.csv")
Butcher <- read_csv("Butcher Data/butcher_clean_2.csv")
Cartographer <- read_csv("Cartographer Data/cartographer_clean_2.csv")
Cleric <- read_csv("Cleric Data/cleric_clean_2.csv")
Farmer <- read_csv("Farmer Data/farmer_clean_2.csv")
Fisherman <- read_csv("Fisherman Data/fisherman_clean_2.csv")
Fletcher <- read_csv("Fletcher Data/fletcher_clean_2.csv")
Leatherworker <- read_csv("Leatherworker Data/leatherworker_clean_2.csv")
Librarian <- read_csv("Librarian Data/librarian_clean_2.csv")
Mason <- read_csv("Mason Data/mason_clean_2.csv")
Shepherd <- read_csv("Shepherd Data/shepherd_clean_2.csv")
Toolsmith <- read_csv("Toolsmith Data/toolsmith_clean_2.csv")
Weaponsmith <- read_csv("Weaponsmith Data/weaponsmith_clean_2.csv")

```

```{r}
Armorer <- Armorer %>% 
  unite(row_id, row_id, trade)
Butcher <- Butcher %>% 
  unite(row_id, row_id, trade)
Cartographer <- Cartographer %>% 
  unite(row_id, row_id, trade)
Cleric <- Cleric %>% 
  unite(row_id, row_id, trade)
Farmer <- Farmer %>% 
  unite(row_id, row_id, trade)
Fisherman <- Fisherman %>% 
  unite(row_id, row_id, trade)
Fletcher <- Fletcher %>% 
  unite(row_id, row_id, trade)
Leatherworker <- Leatherworker %>% 
  unite(row_id, row_id, trade)
Librarian <- Librarian %>% 
  unite(row_id, row_id, trade)
Mason <- Mason %>% 
  unite(row_id, row_id, trade)
Shepherd <- Shepherd %>% 
  unite(row_id, row_id, trade)
Toolsmith <- Toolsmith %>% 
  unite(row_id, row_id, trade)
Weaponsmith <- Weaponsmith %>% 
  unite(row_id, row_id, trade)
```

```{r}
names <- c("row_id", "level", "bedrock_edition_slot", "bedrock_edition_probability", "java_edition_probability", "em_wanted", "num_em_want_low", "num_em_want_high", "item_wanted", "num_item_want", "em_given", "num_em_given", "item_given", "num_item_given", "trades_in_stock", "price_multiplier", "villager_xp")
```

```{r}
Armorer <- Armorer %>% 
  rename_with(~ names)
Butcher <- Butcher %>% 
  rename_with(~ names)
Cartographer <- Cartographer %>% 
  rename_with(~ names)
Cleric <- Cleric %>% 
  rename_with(~ names)
Farmer <- Farmer %>% 
  rename_with(~ names)
Fisherman <- Fisherman %>% 
  rename_with(~ names)
Fletcher <- Fletcher %>% 
  rename_with(~ names)
Leatherworker <- Leatherworker %>% 
  rename_with(~ names)
Librarian <- Librarian %>% 
  rename_with(~ names)
Mason <- Mason %>% 
  rename_with(~ names)
Shepherd <- Shepherd %>% 
  rename_with(~ names)
Toolsmith <- Toolsmith %>% 
  rename_with(~ names)
Weaponsmith <- Weaponsmith %>% 
  rename_with(~ names)
```

```{r}
AB <- full_join(Armorer, Butcher, by="row_id")
AB %>% 
  unite(level, level.x, level.y, sep = " ", na.rm = TRUE) %>% 
  unite(bedrock_edition_slot, bedrock_edition_slot.x, bedrock_edition_slot.y, na.rm = TRUE) %>% 
  unite(bedrock_edition_probability, bedrock_edition_probability.x, bedrock_edition_probability.y, na.rm = TRUE) %>% 
  unite(java_edition_probability, java_edition_probability.x, java_edition_probability.y, na.rm = TRUE) %>% 
  unite(em_wanted, em_wanted.x, em_wanted.y, na.rm = TRUE) %>% 
  unite(num_em_want_low, num_em_want_low.x, num_em_want_low.y, na.rm = TRUE) %>% 
  unite(num_em_want_high, num_em_want_high.x, num_em_want_high.y, na.rm = TRUE) %>% 
  unite(item_wanted, item_wanted.x, item_wanted.y, na.rm = TRUE) %>% 
  unite(num_item_want, num_item_want.x, num_item_want.y, na.rm = TRUE) %>% 
  unite(em_given, em_given.x, em_given.y, na.rm = TRUE) %>% 
  unite(num_em_given, num_em_given.x, num_em_given.y, na.rm = TRUE) %>% 
  unite(trades_in_stock, trades_in_stock.x, trades_in_stock.y, na.rm = TRUE) %>% 
  unite(price_multiplier, price_multiplier.x, price_multiplier.y, na.rm = TRUE) %>% 
  unite(villager_xp, villager_xp.x, villager_xp.y, na.rm = TRUE)

CC <- full_join(Cartographer, Cleric, by="row_id")
FF <- full_join(Farmer, Fisherman, by="row_id")
FL <- full_join(Fletcher, Leatherworker, by="row_id")
LM <- full_join(Librarian, Mason, by="row_id")
ST <- full_join(Shepherd, Toolsmith, by="row_id")
Weaponsmith
```

```{r}
ABCC <- full_join(AB, CC, by="row_id")
FFFL <- full_join(FF, FL, by="row_id")
LMST <- full_join(LM, ST, by="row_id")
Weaponsmith
```

```{r}
ABCCFFFL <- full_join(ABCC, FFFL, by="row_id")
LMSTW <- full_join(LMST, Weaponsmith, by="row_id")
```

```{r}
villager_combo <- full_join(ABCCFFFL, LMSTW, by="row_id")
```

