---
title: "Armorer"
output: html_document
---

```{r}
library(tidyverse)
library(RColorBrewer)
library(paletteer)
library(janitor)
library(gtools)
```

```{r}
Armorer <- read_csv("Armorer.csv")
names(Armorer)
```

```{r}
armorer_names2 <- Armorer[1:2, ]
```

```{r}
armorer_names3 <- armorer_names2 %>%
  pivot_longer(everything(), names_to = "variable", values_to = "value") %>%
  # Add a row identifier
  mutate(row_id = rep(1:nrow(armorer_names2), each = ncol(armorer_names2))) %>%
  # Reshape back to wide format with rows as columns
  pivot_wider(names_from = row_id, values_from = value, names_prefix = "Row_")
armorer_names3
```

```{r}
armorer_names3 <- armorer_names3 %>% 
  clean_names()
armorer_names3
```

```{r}
armorer_names4 <- armorer_names3 %>% 
  #filter(is.na(row_2) == TRUE)
  mutate(new_names = case_when(is.na(row_1) == FALSE & is.na(row_2) == FALSE ~ paste(row_1, row_2, sep = " "), is.na(row_2) == TRUE ~ row_1, is.na(row_1) == TRUE ~ row_2)) %>%   mutate(new_names = ifelse(new_names == "Probability", "Bedrock Edition Probability", new_names))
```

```{r}
armorer_names4$new_names <- str_remove(armorer_names4$new_names, "\n")
armorer_names4
```

```{r}
armorer2 <- Armorer %>%
  rename_with(~ armorer_names4$new_names) %>% 
  clean_names()
armorer2 <- armorer2[-c(1, 2), ]
armorer2
```

```{r}
armorer2.1 <- armorer2 %>% 
  mutate(level = case_when(villager_xp == "1" ~ "Novice", 
                           villager_xp == "2" ~ "Novice",
                           villager_xp == "5" | villager_xp == "10" & item_wanted == "4 × Iron Ingot" ~ "Apprentice",
                           villager_xp == "20" | villager_xp == "10" & item_wanted != "4 × Iron Ingot" ~ "Journeyman",
                           villager_xp == "15" ~ "Expert",
                           villager_xp == "30" ~ "Master"))
armorer2.1
```

```{r}
armorer2.1$bedrock_edition_slot <- as.integer(armorer2.1$bedrock_edition_slot)

armorer2.1$bedrock_edition_probability <- str_remove(armorer2.1$bedrock_edition_probability, "%")

armorer2.1$bedrock_edition_probability <- as.integer(armorer2.1$bedrock_edition_probability)

armorer2.1$java_edition_probability <- str_remove(armorer2.1$java_edition_probability, "%")

armorer2.1$java_edition_probability <- as.integer(armorer2.1$java_edition_probability)

armorer2.1$trades_instock <- as.integer(armorer2.1$trades_instock)

armorer2.1$villager_xp <- as.integer(armorer2.1$villager_xp)

armorer2.1
```

```{r}
armorer2.2 <- armorer2.1 %>% 
  mutate(bedrock_edition_slot = case_when(villager_xp == "1" ~ 2, 
                           villager_xp == "5" ~ 4,
                           villager_xp == "10" & bedrock_edition_probability == 33 ~ 7,
                           villager_xp == "15" ~ 8,
                           villager_xp == "30" ~ 9,
                           TRUE ~ bedrock_edition_slot))
armorer2.2
```

```{r}
armorer2.3 <- armorer2.2 %>% 
  #mutate(if_else())
  separate(item_given, into= c("item_given", "garbage"), sep = "\\[")
armorer2.3 <- armorer2.3[ ,-7]
armorer2.3
```

```{r}
armorer2.4 <- armorer2.3 %>% 
  #mutate(if_else())
  separate(item_wanted, into= c("low_range", "item_wanted"), sep = "×") %>% 
  mutate(item_wanted = if_else(is.na(item_wanted) == TRUE, low_range, item_wanted)) %>% 
  mutate(low_range = if_else(low_range != item_wanted, low_range, "1"))
armorer2.4
```

```{r}
armorer2.5 <- armorer2.4 %>% 
  #mutate(if_else())
  separate(low_range, into= c("low_range_2", "high_range"), sep = "\\-") #%>% 
  #mutate(item_wanted = if_else(is.na(item_wanted) == TRUE, low_range, item_wanted)) %>% 
  #mutate(low_range = if_else(low_range != item_wanted, low_range, "1"))
armorer2.5
```

