---
title: "Butcher"
output: html_document
---
```{r}
library(tidyverse)
library(RColorBrewer)
library(paletteer)
library(janitor)
library(gtools)
```

```{r}
butcher_og <- read_csv("Butcher_og.csv")
names(butcher_og)
```

```{r}
butcher_names <- butcher_og[1:2, ]
```

```{r}
butcher_names2 <- butcher_names %>%
  
  pivot_longer(everything(), names_to = "variable", values_to = "value") %>%
  # Add a row identifier
  mutate(row_id = rep(1:nrow(butcher_names), each = ncol(butcher_names))) %>%
  # Reshape back to wide format with rows as columns
  pivot_wider(names_from = row_id, values_from = value, names_prefix = "Row_")
butcher_names2
```
```{r}
butcher_names3 <- butcher_names2 %>% 
  clean_names()
butcher_names3
```

```{r}
butcher_names4 <- butcher_names3 %>% 
  #filter(is.na(row_2) == TRUE)
  mutate(new_names = case_when(is.na(row_1) == FALSE & is.na(row_2) == FALSE ~ paste(row_1, row_2, sep = " "), is.na(row_2) == TRUE ~ row_1, is.na(row_1) == TRUE ~ row_2)) %>%   mutate(new_names = ifelse(new_names == "Probability", "Bedrock Edition Probability", new_names))
butcher_names4
```

```{r}
butcher_names4$new_names <- str_remove(butcher_names4$new_names, "\n")
butcher_names4
```

```{r}
butcher2 <- butcher_og %>%
  rename_with(~ butcher_names4$new_names) %>% 
  clean_names()
butcher2 <- butcher2[-c(1, 2), ]
butcher2
```

```{r}
butcher2.1 <- butcher2 %>% 
  mutate(level = case_when(java_edition_probability == "50%" & villager_xp == "2" | villager_xp == "1"~ "Novice", 
                           villager_xp == "5" ~ "Apprentice",
                           villager_xp == "20" ~ "Journeyman",
                           TRUE ~ level))
butcher2.1
```

```{r}
butcher2.1$bedrock_edition_slot <- as.integer(butcher2.1$bedrock_edition_slot)

butcher2.1$bedrock_edition_probability <- str_remove(butcher2.1$bedrock_edition_probability, "%")

butcher2.1$bedrock_edition_probability <- as.integer(butcher2.1$bedrock_edition_probability)

butcher2.1$java_edition_probability <- str_remove(butcher2.1$java_edition_probability, "%")

butcher2.1$java_edition_probability <- as.integer(butcher2.1$java_edition_probability)

butcher2.1$trades_instock <- as.integer(butcher2.1$trades_instock)

butcher2.1$villager_xp <- as.integer(butcher2.1$villager_xp)

butcher2.1
```

```{r}
butcher2.2 <- butcher2.1 %>% 
  mutate(bedrock_edition_slot = case_when(villager_xp == 20 ~ 5,
                           villager_xp == 5 ~ 4,
                           bedrock_edition_probability == 33 ~ 1,
                           TRUE ~ bedrock_edition_slot))
butcher2.2
```

```{r}
butcher2.4 <- butcher2.2 %>% 
  #mutate(if_else())
  separate(item_wanted, into= c("num_item_wanted", "item_wanted"), sep = "×") %>% 
  mutate(item_wanted = if_else(is.na(item_wanted) == TRUE, num_item_wanted, item_wanted)) %>% 
  mutate(num_item_wanted = if_else(num_item_wanted != item_wanted, num_item_wanted, "1"))

butcher2.4$num_item_wanted = as.integer(butcher2.4$num_item_wanted)
butcher2.4
```

```{r}
butcher2.5 <- butcher2.4 %>% 
  separate(item_given, into= c("num_item_given", "item_given"), sep = "×") %>% 
  mutate(item_given = if_else(is.na(item_given) == TRUE, num_item_given, item_given)) %>% 
  mutate(num_item_given = if_else(num_item_given != item_given, num_item_given, "1"))

butcher2.5$num_item_given = as.integer(butcher2.5$num_item_given)
butcher2.5
```

```{r}
write.csv(butcher2.5, "butcher_clean_1.csv", row.names = FALSE)
butcher <- read_csv("butcher_clean_1.csv")
```

